language: ruby
sudo: required
rvm:
- 2.1

before_script:
  - chmod +x ./script/cibuild

# Assume bundler is being used, install step will run `bundle install`.
script: ./script/cibuild

# branch whitelist
branches:
  only:
  - master     # test the master branch

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer