# Site settings
title: upbit solutions
email: hello@upbitsolutions.pt
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://upbitsolutions.pt" # the base hostname & protocol for your site
twitter_username: upbitsolutions
github_username:  upbitsolutions
exclude: [vendor]
# Build settings
markdown: kramdown
highlighter: rouge  
jekyll-press:
  exclude: 'atom.xml' # Exclude files from processing - file name, glob pattern or array of file names and glob patterns
  js_options: {}      # js minifier options
  css_options: {}     # css minifier options
  html_options: {}    # html minifier options